env:
  es2021: true
extends:
  - standard
  - prettier
  - plugin:jsonc/recommended-with-json
  - plugin:jsonc/prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - sort-keys-fix
rules:
  sort-keys-fix/sort-keys-fix: warn
  jsonc/sort-keys: warn
