name: Build
on: workflow_call
concurrency:
  group: ${{ github.ref_name }}-build
  cancel-in-progress: true
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
  archive:
    name: Archive
    runs-on: ubuntu-latest
    needs: test
    outputs:
      ARCHIVE: ${{ steps.package.outputs.ARCHIVE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Package
        id: package
        run: echo "ARCHIVE=$(npm pack -s)" >> $GITHUB_OUTPUT
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: "${{ steps.package.outputs.ARCHIVE }}"
          path: "${{ steps.package.outputs.ARCHIVE }}"
  start-publish:
    name: Start Publish
    needs: archive
    uses: ./.github/workflows/publish.yml
    with:
      archive: ${{ needs.archive.outputs.ARCHIVE }}
