name: Pipeline
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - master
concurrency:
  group: ${{ github.ref_name }}-source
  cancel-in-progress: true
jobs:
  generation:
    name: Generation
    runs-on: ubuntu-latest
    outputs:
      FILES_CHANGED: ${{ steps.files_changed.outputs.FILES_CHANGED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Lint Fix
        run: npm run eslint:fix
      - name: Prettier Fix
        run: npm run prettier:fix
      - name: Generate Docs
        run: npm run docs
      - name: Generate Typescript Types
        run: npm run tsc
      - id: files_changed
        name: Files Changed?
        run: |
          if [ "" == "$(git status -s)" ]; then
            echo "FILES_CHANGED=false" >> $GITHUB_OUTPUT
          else
            echo "FILES_CHANGED=true" >> $GITHUB_OUTPUT
          fi
      - name: Push Generated Code
        if: steps.files_changed.outputs.FILES_CHANGED == 'true'
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Automatic Commit of Generated Files."
          git push origin ${{ github.ref_name }}
      - name: Restart Source Workflow
        if: steps.files_changed.outputs.FILES_CHANGED == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Source Generation
  start-build:
    name: Build
    needs: generation
    if: needs.generation.outputs.FILES_CHANGED == 'false'
    uses: ./.github/workflows/build.yml
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
