name: Retry
on: workflow_dispatch
concurrency:
  group: ${{ github.ref_name }}-automate
  cancel-in-progress: true
jobs:
  retry:
    name: Retry
    uses: ./.github/workflows/build.yml
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
